/**
 * PROJECT: Crypto Lakeside Institutional Terminal
 * MODULE: HomePage (Master Refactor)
 * VERSION: 3.1.0
 * DEVELOPER: Abhishek Topu (SAP Certified)
 * ARCHITECTURE: Sentiment-Driven Analytics + High-Density Live Feed
 */

import React, { useEffect, useState } from "react";

// Institutional Layout Components
import Header from "../components/Header/Header.js";
import HeaderLinks from "../components/Header/HeaderLinks.js";

const HomePage = (props) => {
  // --- CORE SYSTEM STATE ---
  const [usersOnline, setUsersOnline] = useState(157);
  const [recentUser, setRecentUser] = useState("");
  const [lastHeartbeat, setLastHeartbeat] = useState(new Date().toLocaleTimeString());
  
  // Unified Institutional Data State
  const [marketData, setMarketData] = useState({
      sentiment: { value: "13", classification: "Extreme Fear" },
      prices: { BTC: "0", ETH: "0", SOL: "0" },
      trades: []
  });

  // Institutional Leaderboard Data
  const traders = [
    { nickname: "Rubedo Engine", roi: "81.28", maxDrawdown: "0.23", aum: "$1.2M", color: "#f3ba2f" },
    { nickname: "caleon8", roi: "52.08", maxDrawdown: "0.00", aum: "$850K", color: "#000000" },
    { nickname: "Liafe", roi: "48.57", maxDrawdown: "4.32", aum: "$500K", color: "#0088cc" }
  ];

  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = "Institutional Terminal | Crypto Lakeside";

    /**
     * DATA SYNCHRONIZATION SERVICE
     * Pulls the high-density feed generated by whale_tracker.py
     */
    const performDataSync = () => {
        fetch('/whales.json')
            .then(res => res.json())
            .then(data => {
                setMarketData(data);
                setLastHeartbeat(new Date().toLocaleTimeString());
            })
            .catch(err => console.log("System Sync in Progress..."));
    };

    // Execute initial load and 30-second refresh cycle
    performDataSync();
    const syncCycle = setInterval(performDataSync, 30000); 

    // UI REFINEMENT: Remove extraneous WhatsApp buttons/overlays
    const cleanTerminalUI = () => {
        const buttons = document.querySelectorAll('a[href*="wa.me"], div[class*="whatsapp"], button[class*="whatsapp"]');
        buttons.forEach(btn => btn.style.display = 'none');
    };
    cleanTerminalUI();

    // NODE CONNECTIVITY NOTIFICATIONS
    const notifyCycle = setInterval(() => {
      const hubs = ["Dubai", "London", "Singapore", "New York", "Hong Kong", "Mumbai"];
      const hub = hubs[Math.floor(Math.random() * hubs.length)];
      setRecentUser(`Institutional Node ${hub} terminal authorized 🛡️`);
      setTimeout(() => setRecentUser(""), 5000);
    }, 28000);

    return () => { 
        clearInterval(syncCycle); 
        clearInterval(notifyCycle); 
    };
  }, []);

  /**
   * TRANSACTION HANDLER
   * Optimized for Bybit Affiliate Hub stability (India FIU Compliance)
   */
  const handleRedirect = (origin) => {
    const refId = "157106";
    const targetUrl = `https://www.bybit.com/copyTrade/?ref=${refId}`;

    // Google Tag Manager Event Capture (G-2Y9M643E6E)
    if (window.gtag) { 
        window.gtag('event', 'generate_lead', { 
            'platform': 'Bybit_Terminal',
            'lead_origin': origin
        }); 
    }

    window.open(targetUrl, "_blank");
  };

  return (
    <div className="terminal_wrapper" style={styles.mainWrapper}>
      {/* INSTITUTIONAL HEADER */}
      <Header
        color="white"
        brand={
          <a href="/" style={styles.brandLink}>
            <div style={styles.logoCircle}>CL</div>
            <div style={styles.brandText}>
                <span style={{ color: "#000", fontWeight: "900" }}>CRYPTO</span>
                <span style={{ color: "#f3ba2f", fontWeight: "900" }}>LAKESIDE</span>
            </div>
          </a>
        }
        rightLinks={<HeaderLinks />}
        {...props}
      />

      {/* HERO SECTION */}
      <div style={styles.heroSection}>
        <div className="container" style={{ maxWidth: "1100px", margin: "0 auto" }}>
          <h1 style={styles.mainTitle}>Institutional Trading Terminal</h1>
          <p style={styles.heroSubText}>
              High-Alpha execution monitoring. Mirror verified performance from 
              the world's most liquid derivatives markets.
          </p>
          <div style={styles.statusPill}>
            <span style={styles.pulseDot}></span> {usersOnline} Institutions Active
          </div>
          <div style={{ marginTop: "40px" }}>
            <button style={styles.ctaButton} onClick={() => handleRedirect("Hero_Main")}>
                ENTER TRADING TERMINAL
            </button>
          </div>
        </div>
      </div>

      {/* MARKET INTELLIGENCE GRID (FIXED SOL ALIGNMENT) */}
      <div style={styles.dataSection}>
          <div className="container" style={{ maxWidth: "1200px", margin: "0 auto" }}>
            
            {/* 4-COLUMN GRID: SENTIMENT + BTC + ETH + SOL */}
            <div style={styles.dashboardGrid}>
                <div style={styles.dashboardCard}>
                    <p style={styles.statLabel}>MARKET SENTIMENT</p>
                    <h2 style={{ color: marketData.sentiment.value < 40 ? "#ef4444" : "#4ade80", fontWeight: "900", margin: 0 }}>
                        {marketData.sentiment.classification.toUpperCase()} ({marketData.sentiment.value})
                    </h2>
                </div>
                {['BTC', 'ETH', 'SOL'].map(coin => (
                    <div key={coin} style={styles.dashboardCard}>
                        <p style={styles.statLabel}>{coin} INDEX PRICE (USD)</p>
                        <h2 style={{ color: "#ffffff", fontWeight: "900", margin: 0 }}>
                            ${parseFloat(marketData.prices[coin] || 0).toLocaleString()}
                        </h2>
                    </div>
                ))}
            </div>

            {/* LIVE SCROLLING EXECUTION FEED */}
            <div style={styles.terminalContainer}>
                <div style={styles.terminalHeader}>
                    <div style={styles.terminalDot}></div> 
                    <span style={styles.terminalTitle}>LIVE WHALE EXECUTION FLOW (CORE FEED)</span>
                    <span style={styles.syncTag}>LAST HEARTBEAT: {lastHeartbeat}</span>
                </div>
                <div style={styles.terminalBody}>
                    <div style={styles.scrollWrapper}>
                        {marketData.trades.length > 0 ? marketData.trades.map((trade, i) => (
                            <div key={i} style={styles.whaleRow}>
                                <span style={{ color: "#64748b", width: "100px", display: "inline-block" }}>[{new Date(parseInt(trade.time)).toLocaleTimeString()}]</span>
                                <span style={{ color: "#f3ba2f", fontWeight: "900", width: "50px", display: "inline-block" }}>{trade.symbol}</span>
                                <span style={{ color: trade.side === "Buy" ? "#4ade80" : "#ef4444", fontWeight: "bold", width: "60px", display: "inline-block" }}>{trade.side.toUpperCase()}</span>
                                <span style={{ color: "#ffffff", fontWeight: "800", width: "140px", display: "inline-block" }}>{trade.value}</span>
                                <span style={{ color: "#94a3b8" }}>@ {trade.price}</span>
                            </div>
                        )) : <div style={{ padding: "20px", color: "#94a3b8" }}>Aggregating institutional flow...</div>}
                        
                        {/* Duplicate Data for Infinite Scroll Continuity */}
                        {marketData.trades.map((trade, i) => (
                            <div key={`d-${i}`} style={styles.whaleRow}>
                                <span style={{ color: "#64748b", width: "100px", display: "inline-block" }}>[{new Date(parseInt(trade.time)).toLocaleTimeString()}]</span>
                                <span style={{ color: "#f3ba2f", fontWeight: "900", width: "50px", display: "inline-block" }}>{trade.symbol}</span>
                                <span style={{ color: trade.side === "Buy" ? "#4ade80" : "#ef4444", fontWeight: "bold", width: "60px", display: "inline-block" }}>{trade.side.toUpperCase()}</span>
                                <span style={{ color: "#ffffff", fontWeight: "800", width: "140px", display: "inline-block" }}>{trade.value}</span>
                                <span style={{ color: "#94a3b8" }}>@ {trade.price}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
          </div>
      </div>

      {/* LEADERBOARD SECTION */}
      <div style={styles.leaderboardSection}>
          <div className="container" style={{ maxWidth: "1100px", margin: "0 auto" }}>
              <h3 style={styles.sectionTitle}>Institutional Performance Leaderboard</h3>
              <div style={styles.traderGrid}>
                  {traders.map((trader, idx) => (
                      <div key={idx} style={styles.traderCard}>
                          <div style={styles.cardHeader}>
                              <div style={{...styles.traderIcon, background: trader.color}}>{trader.nickname[0]}</div>
                              <h4 style={styles.traderName}>{trader.nickname}</h4>
                          </div>
                          <div style={styles.statBox}>
                              <div style={styles.statItem}>
                                  <p style={styles.labelSmall}>ROI (30D)</p>
                                  <p style={{ color: "#4ade80", fontWeight: "900", fontSize: "24px" }}>+{trader.roi}%</p>
                              </div>
                              <div style={styles.statItem}>
                                  <p style={styles.labelSmall}>DRAWDOWN</p>
                                  <p style={{ color: "#fff", fontWeight: "900", fontSize: "24px" }}>{trader.maxDrawdown}%</p>
                              </div>
                          </div>
                          <button style={styles.copyBtn} onClick={() => handleRedirect("Copy_Leaderboard")}>MIRROR STRATEGY</button>
                      </div>
                  ))}
              </div>
          </div>
      </div>

      {/* FOOTER & COMPLIANCE */}
      <footer style={styles.footer}>
          <div style={{ marginBottom: "30px" }}>
            <button style={styles.binanceBtn} onClick={() => handleRedirect("Binance_Portal")}>ACCESS BINANCE TERMINAL</button>
          </div>
          <p style={{ fontSize: "11px", fontWeight: "700", opacity: "0.5", letterSpacing: "1px" }}>OFFICIAL GLOBAL PARTNER | SECURED DATA FEED BYBIT V5 / BITFINEX</p>
          <p style={{ fontSize: "10px", opacity: "0.3", marginTop: "15px", maxWidth: "800px", margin: "15px auto" }}>Trading involve risk. Past performance is not a guarantee of future results.</p>
      </footer>

      {/* TOAST NOTIFICATION */}
      {recentUser && <div style={styles.toast}>{recentUser}</div>}

      {/* ANIMATION ENGINE */}
      <style>{`
        @keyframes scrollTerminal {
          0% { transform: translateY(0); }
          100% { transform: translateY(-50%); }
        }
      `}</style>
    </div>
  );
};

// --- ENTERPRISE STYLING ARCHITECTURE ---
const styles = {
  mainWrapper: { backgroundColor: "#0f172a", color: "#f8fafc", fontFamily: "'Barlow', sans-serif" },
  brandLink: { display: "flex", alignItems: "center", textDecoration: "none" },
  logoCircle: { background: "#f3ba2f", color: "#000", width: "36px", height: "36px", display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "6px", fontWeight: "900" },
  brandText: { marginLeft: "12px", fontSize: "20px", display: "flex", gap: "6px" },
  
  heroSection: { padding: "140px 20px 80px", textAlign: "center", background: "radial-gradient(circle at center, #1e293b 0%, #0f172a 100%)" },
  mainTitle: { fontWeight: "900", fontSize: "48px", color: "#fff", letterSpacing: "-1.5px" },
  heroSubText: { color: "#94a3b8", fontSize: "20px", margin: "20px auto", maxWidth: "700px" },
  
  statusPill: { display: "inline-flex", alignItems: "center", background: "rgba(34, 197, 94, 0.1)", padding: "10px 25px", borderRadius: "6px", color: "#4ade80", fontWeight: "700", border: "1px solid rgba(74, 222, 128, 0.2)" },
  pulseDot: { height: "8px", width: "8px", backgroundColor: "#4ade80", borderRadius: "50%", marginRight: "12px", boxShadow: "0 0 12px #4ade80" },
  ctaButton: { background: "#f3ba2f", color: "#000", padding: "20px 60px", fontSize: "17px", fontWeight: "900", borderRadius: "6px", border: "none", cursor: "pointer" },
  
  dataSection: { padding: "40px 20px" },
  dashboardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "20px", marginBottom: "30px" },
  dashboardCard: { background: "#1e293b", padding: "30px", borderRadius: "12px", border: "1px solid #334155" },
  statLabel: { fontSize: "11px", color: "#64748b", fontWeight: "900", marginBottom: "8px", letterSpacing: "1.2px", textTransform: "uppercase" },
  
  terminalContainer: { background: "#1e293b", borderRadius: "12px", border: "1px solid #334155", overflow: "hidden" },
  terminalHeader: { background: "#1e293b", padding: "15px 25px", display: "flex", alignItems: "center", borderBottom: "1px solid #334155" },
  terminalDot: { height: "10px", width: "10px", background: "#ef4444", borderRadius: "50%", marginRight: "18px", boxShadow: "0 0 10px #ef4444" },
  terminalTitle: { fontWeight: "800", fontSize: "12px", color: "#94a3b8", letterSpacing: "1px" },
  syncTag: { marginLeft: "auto", fontSize: "10px", color: "#64748b" },
  
  terminalBody: { background: "#020617", height: "450px", overflow: "hidden", position: "relative" },
  scrollWrapper: { padding: "25px", animation: "scrollTerminal 60s linear infinite" },
  whaleRow: { padding: "12px 0", borderBottom: "1px solid #1e293b", fontSize: "14px", fontFamily: "monospace", letterSpacing: "0.8px" },

  leaderboardSection: { padding: "100px 20px", background: "#0f172a" },
  sectionTitle: { fontWeight: "900", fontSize: "36px", color: "#fff", textAlign: "center", marginBottom: "60px" },
  traderGrid: { display: "flex", flexWrap: "wrap", gap: "35px", justifyContent: "center" },
  traderCard: { background: "#1e293b", padding: "35px", borderRadius: "16px", width: "350px", border: "1px solid #334155", textAlign: "center" },
  cardHeader: { display: "flex", alignItems: "center", marginBottom: "30px", justifyContent: "center" },
  traderIcon: { width: "50px", height: "50px", borderRadius: "8px", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", fontSize: "22px" },
  traderName: { fontWeight: "800", marginLeft: "18px", color: "#fff", fontSize: "24px" },
  statBox: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "25px", marginBottom: "35px" },
  labelSmall: { fontSize: "10px", color: "#64748b", fontWeight: "900", marginBottom: "5px" },
  copyBtn: { width: "100%", padding: "16px", background: "transparent", color: "#f3ba2f", borderRadius: "4px", fontWeight: "800", border: "2px solid #f3ba2f", cursor: "pointer" },
  
  binanceBtn: { background: "#fff", color: "#000", padding: "15px 40px", borderRadius: "6px", border: "none", fontWeight: "900", cursor: "pointer" },
  footer: { padding: "80px 20px", textAlign: "center", background: "#020617", borderTop: "1px solid #1e293b" },
  toast: { position: "fixed", bottom: "40px", left: "40px", background: "#1e293b", color: "#fff", padding: "18px 30px", borderRadius: "8px", borderLeft: "5px solid #f3ba2f", zIndex: 10000, boxShadow: "0 15px 40px rgba(0,0,0,0.6)" }
};

export default HomePage;
