name: Hourly Whale Update
on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run Whale Tracker
        run: python whale_tracker.py
        
      - name: Sync and Push Data
        run: |
          git config --global user.name 'WhaleBot'
          git config --global user.email 'bot@cryptolakeside.co.in'
          
          # Stage the new data first
          git add public/whales.json
          
          # Pull any changes you made in the browser and merge the data
          git pull --rebase --autostash origin main
          
          # Save and send to the website
          git commit -m "Automated Data Update" || exit 0
          git push origin main
